name = "sarlhego"
compatibility_date = "2025-03-21"

workers_dev = false

assets = { directory = "./build", html_handling = "force-trailing-slash"}
upload_source_maps = false

[[routes]]
pattern = "sarlhego.axelhego.fr/*"
zone_id = "axelhego.fr"
custom_domain = true