name = "sarlhego"
compatibility_date = "2025-03-21"

workers_dev = false
upload_source_maps = false

[assets]
directory = "./build"
html_handling = "force-trailing-slash"
not_found_handling = "single-page-application"

[[routes]]
pattern = "sarlhego.axelhego.fr"
zone_name = "axelhego.fr"
custom_domain = true